{
 "title": "API Health",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(api_response_time_ms_bucket,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Response TIme",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(api_response_time_ms_bucket{endpoint=\"$endpoint\"}[5m]))",
     "legendFormat": "p99_latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(api_response_time_ms_bucket{endpoint=\"$endpoint\"}[5m]))",
     "legendFormat": "p95_latency"
    },
    {
     "expr": "histogram_quantile(0.90, rate(api_response_time_ms_bucket{endpoint=\"$endpoint\"}[5m]))",
     "legendFormat": "p90_latency"
    },
    {
     "expr": "histogram_quantile(0.50, rate(api_response_time_ms_bucket{endpoint=\"$endpoint\"}[5m]))",
     "legendFormat": "p50_latency"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_group) (rate(api_error_count{endpoint=\"$endpoint\"}[5m]))",
     "legendFormat": "{{status_group}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_availability{endpoint=\"$endpoint\"}",
     "legendFormat": "upTIme"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(api_requests_total{endpoint=\"$endpoint\"}[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "api_saturation{resource=\"CPU\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "api_saturation{resource=\"Memory\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}